### ISSUE TITLE
Artes Method Xillia 2

### ISSUE THREAD

**Issue by marc726** [Sora3100/Tales_of_Cheat_Tables#7]
Hi! Apologies for the silly question, but could you please shed light on how you found the array for artes/skills. I'm trying to learn CE for myself and Artes for Xillia 2 is honestly extremely confusing. 

The method I did was scan for changed values when leveling up with allium, reloading save and repeating. I don't understand how you figured out the array of bytes used to unlock artes.

**Comment by Sora3100** [comment]
The way I found skills were just enabling and disabling them in the skill menu, and scanning each change, then I looked at memory view and noticed that there was a section that looked near identical, I messed with those and noticed skills show up.

As for artes, I believe it might have been a similiar method where I was enabling/disabling artes on bots, but I'm not 100% sure, it's been a while since I did it. If you messed with other Tales games before, sometimes they like to put artes right next to where stats are.

Your method isn't a bad one, but it might take quite long. (If it wasn't on an emulator it might have not even worked)

As for how they work, they are a binary operation. Look at the status effects readme in the table, they work the exact same way.

Hope this helps!

**Comment by marc726** [comment]
Oh! Binary would explain odd byte values. Didn't even think about it like that. Thank you so much for answering! Sorry one last question though.

So when you were testing out skills/artes unlocks did you do trial and error at each individual byte address? I noticed frequent instances of 00 bytes in between and after the db for each character.

**Comment by Sora3100** [comment]
I just took the bytes from a finished save file, a lot of them don't really do anything without further hacking, since the game has a whitelist for what artes a character can unlock. You can find Ludger's (or Jude, I forgot) whitelist table in the Notes section for example.

Skills is the same for their own, but on the other hand for all skills for everyone, if I remember correctly I just FF'd it all the way to unlock everything
